#**docker-compose.yml**
version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    restart: always
    networks:
      - springmysql-net
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "namroud"
      MYSQL_PASSWORD: "namroud"

  phpmyadmin:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    ports:
      - 9091:80
    networks:
      - springmysql-net

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: demo-docker
    restart: always
    ports:
    - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username:namroud
      - spring.datasource.password=namroud
    networks:
      - springmysql-net
    volumes:
    - .m2:/root/.m2
volumes:
  db:

networks:
  springmysql-net:
    driver: bridge
